services:
  ambassador_backend:
    build: .
    ports:
      - 8003:8000
    volumes:
#      - .:/app
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/storage
    command: 'php artisan serve --host=0.0.0.0'
    depends_on:
      - ambassador_db
    networks:
      - ambassador
      - users

  ambassador_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
#    ports:
#      - 33066:3306
    networks:
      - ambassador

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - ambassador


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8083:80"
    environment:
      PMA_HOST: ambassador_db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - ambassador

#networks:
#  users:
#    external:
#      name: users
networks:
  users:
    external: true
    name: users
  ambassador:

