services:
  backend:
    build: .
    ports:
      - 8000:8000
    volumes:
#      - .:/app
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/storage
    command: 'php artisan serve --host=0.0.0.0'
    depends_on:
      - db
    networks:
      - default
      - users

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33066:3306
    networks:
      - default

#  redis:
#    image: redis
#    ports:
#      - 6379:6379
#    networks:
#      - default


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - default

#networks:
#  users:
#    external:
#      name: users
networks:
  users:
    external:
      name: users


