services:
  checkout_backend:
    build: .
    ports:
      - 8002:8000
    volumes:
#      - .:/app
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/storage
    command: 'php artisan serve --host=0.0.0.0'
    depends_on:
      - checkout_db
    networks:
      - checkout
      - users

  checkout_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: checkout
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
#    ports:
#      - 33066:3306
    networks:
      - checkout


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: checkout_db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - checkout

#networks:
#  users:
#    external:
#      name: users
networks:
  users:
    external: true
    name: users
  checkout:

